name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@98194097d42083daeb6d9f9f42c27f26c4bf7753 # v8.1.24
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@98194097d42083daeb6d9f9f42c27f26c4bf7753 # v8.1.24
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@98194097d42083daeb6d9f9f42c27f26c4bf7753 # v8.1.24
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      - name: Test
        uses: renovatebot/github-action@22e0a16091fc706b04affe6ae53d5e3358ac4023 # v46.1.19
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: full
          RENOVATE_REPOSITORIES: '["vidavidorra/renovate"]'
  release:
    needs:
      - lint-commit-messages
      - lint
      - build
      - test
    uses: vidavidorra/.github/.github/workflows/release.yml@98194097d42083daeb6d9f9f42c27f26c4bf7753 # v8.1.24
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
