name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@0868599570281f6e9fb629b555112bb5d25214e7 # v8.1.19
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@0868599570281f6e9fb629b555112bb5d25214e7 # v8.1.19
  build:
    uses: vidavidorra/.github/.github/workflows/node-build.yml@0868599570281f6e9fb629b555112bb5d25214e7 # v8.1.19
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      - name: Test
        uses: renovatebot/github-action@693b9ef15eec82123529a37c782242f091365961 # v46.1.14
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: full
          RENOVATE_REPOSITORIES: '["vidavidorra/renovate"]'
  release:
    needs:
      - lint-commit-messages
      - lint
      - build
      - test
    uses: vidavidorra/.github/.github/workflows/release.yml@0868599570281f6e9fb629b555112bb5d25214e7 # v8.1.19
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
